var SPREADSHEET_ID = 'YOUR_SPREADSHEET_ID';
var SECRET = 'random_string_here';
var RESPONSE_STATUS = {
  OK: 200,
  CREATED: 201,
  UNAUTHORIZED: 401,
  INTERNAL_ERROR: 500,
  INVALID_REQUEST: 400
};
var VOCABULARY_LANGUAGE = 'en';
var TRANSLATE_LANGUAGE = 'uk';
var DEBUG = false;
